In [1]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_pickle('../../Base de datos/raw/nn_challenge_test.pkl')
df

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
0,0.485838,0.5,0.0,NaN,0.364916,0.000682,0.000000,0.559775,0.000692,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
1,0.471255,0.5,0.0,0.000000,0.432846,0.001364,0.089721,0.740107,0.002308,0.333333,...,0.026009,0.074658,0.003963,1.00000,0.025595,0.106699,0.020597,0.002580,0.0,1
2,0.619600,0.5,0.0,0.000000,0.208381,0.002046,0.424221,0.668134,0.000857,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
3,0.600626,1.0,0.0,0.000018,0.146909,0.015007,0.583363,0.858019,0.001088,0.500000,...,0.176415,0.238134,0.005945,0.80770,0.043148,0.250982,0.199603,0.004473,0.0,1
4,0.642833,1.0,0.0,0.000259,0.177191,0.042974,0.583363,0.691851,0.000956,0.750000,...,0.211176,0.106760,0.001321,0.75000,0.122571,0.238861,0.106760,0.005346,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270950,0.514214,0.0,0.0,0.000000,0.089995,0.019100,0.291681,0.440296,0.004814,0.333333,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
270951,0.405381,0.5,0.0,0.000105,0.249793,0.006139,0.116673,0.552868,0.002638,0.500000,...,0.112360,0.020824,0.005284,0.85000,0.042598,0.207764,0.020597,0.003336,1.0,1
270952,0.691027,0.5,0.0,0.000164,0.355698,0.003411,0.145841,0.869412,0.000890,0.666667,...,0.064070,0.030698,0.019815,0.92645,0.031424,0.221957,0.020597,0.004713,0.0,1
270953,0.712737,0.5,0.0,0.000000,0.231467,0.010914,0.291681,0.701853,0.000725,0.000000,...,0.039394,0.112085,0.000661,0.50000,0.040467,0.110831,0.112085,0.001517,1.0,1
270954,0.670764,0.0,0.0,0.000000,0.276833,0.004775,0.291681,0.615141,0.001187,0.000000,...,0.045928,0.059760,0.003303,0.90000,0.030159,0.125187,0.023433,0.003758,1.0,1

In [3]:
df.dtypes.value_counts()

float32     197
float64      10
category      1
category      1
category      1
category      1
category      1
category      1
category      1
object        1
category      1
category      1
category      1
int32         1
Name: count, dtype: int64

# Quitar datos categóricos

In [4]:
# Encuentra las columnas categóricas
categorical_columns = df.select_dtypes(include=['object', 'category']).columns
categorical_columns

Index(['feature_17', 'feature_87', 'feature_118', 'feature_119', 'feature_139',
       'feature_144', 'feature_147', 'feature_148', 'feature_158',
       'feature_159', 'feature_195'],
      dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder

# Crea una instancia del LabelEncoder
le = LabelEncoder()

# Aplica Label Encoding usando apply
df[categorical_columns] = df[categorical_columns].apply(lambda col: le.fit_transform(col))

In [6]:
# Encuentra las columnas categóricas
categorical_columns = df.select_dtypes(include=['object', 'category']).columns
categorical_columns

Index([], dtype='object')

In [7]:
df.dtypes.value_counts()

float32    197
int32       12
float64     10
Name: count, dtype: int64

# Quitar datos nulos

In [8]:
df.isna().sum()

feature_1          0
feature_2          0
feature_3          0
feature_4      20774
feature_5          0
               ...
feature_215        2
feature_216        2
feature_217        2
feature_218        0
target             0
Length: 219, dtype: int64

In [9]:
# Encuentra las columnas que tienen al menos un valor negativo
negative_columns = df.columns[(df < 0).any()].tolist()

# Imprime las columnas con valores negativos
print("Columnas con valores negativos:", negative_columns)

# Número de columnas con valores negativos
num_negative_columns = len(negative_columns)
print(f"Número de columnas con valores negativos: {num_negative_columns}")

Columnas con valores negativos: []
Número de columnas con valores negativos: 0

In [10]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='constant', fill_value=-1)
df_dropped_all = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [11]:
nan_columns = df_dropped_all.columns[df_dropped_all.isna().any()].tolist()
print(f"Columnas con valores NaN: {nan_columns}")

Columnas con valores NaN: []

# Reducción de dimensionalidad

In [12]:
columns_to_remove = ['feature_1',
 'feature_10',
 'feature_101',
 'feature_103',
 'feature_104',
 'feature_109',
 'feature_11',
 'feature_111',
 'feature_113',
 'feature_116',
 'feature_117',
 'feature_12',
 'feature_120',
 'feature_122',
 'feature_124',
 'feature_127',
 'feature_137',
 'feature_144',
 'feature_145',
 'feature_146',
 'feature_152',
 'feature_160',
 'feature_161',
 'feature_165',
 'feature_18',
 'feature_187',
 'feature_19',
 'feature_191',
 'feature_196',
 'feature_198',
 'feature_199',
 'feature_200',
 'feature_202',
 'feature_203',
 'feature_205',
 'feature_206',
 'feature_209',
 'feature_21',
 'feature_210',
 'feature_211',
 'feature_213',
 'feature_214',
 'feature_215',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_28',
 'feature_3',
 'feature_30',
 'feature_31',
 'feature_33',
 'feature_34',
 'feature_37',
 'feature_38',
 'feature_41',
 'feature_47',
 'feature_48',
 'feature_49',
 'feature_5',
 'feature_50',
 'feature_52',
 'feature_53',
 'feature_54',
 'feature_57',
 'feature_62',
 'feature_63',
 'feature_67',
 'feature_69',
 'feature_70',
 'feature_71',
 'feature_77',
 'feature_78',
 'feature_79',
 'feature_8',
 'feature_81',
 'feature_86',
 'feature_9',
 'feature_95',
 'feature_98']

df_dropped_all.drop(columns=columns_to_remove, inplace=True)

In [13]:
df_dropped_all

,feature_2,feature_4,feature_6,feature_7,feature_13,feature_14,feature_15,feature_16,feature_17,feature_20,...,feature_197,feature_201,feature_204,feature_207,feature_208,feature_212,feature_216,feature_217,feature_218,target
0,0.5,-1.000000,0.000682,0.000000,0.0,0.000000,-1.000000,0.0000,3.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
1,0.5,0.000000,0.001364,0.089721,0.0,0.000031,0.013166,0.0000,2.0,0.039216,...,0.034483,0.042598,0.012136,0.013420,0.026187,0.003963,0.020597,0.002580,0.0,1.0
2,0.5,0.000000,0.002046,0.424221,0.0,0.000000,-1.000000,0.0000,7.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
3,1.0,0.000018,0.015007,0.583363,0.0,0.000124,0.113974,0.0000,3.0,0.000000,...,0.022989,0.042971,0.001849,0.011287,0.029193,0.005945,0.199603,0.004473,0.0,1.0
4,1.0,0.000259,0.042974,0.583363,0.0,0.005125,0.877616,0.0106,3.0,0.009804,...,0.017241,0.056945,0.008079,0.000320,0.216927,0.001321,0.106760,0.005346,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270950,0.0,0.000000,0.019100,0.291681,0.0,0.000031,0.006499,0.0000,3.0,0.058824,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
270951,0.5,0.000105,0.006139,0.116673,0.0,0.001770,0.712399,0.0000,3.0,0.000000,...,0.022989,0.045631,0.007853,0.050161,0.115419,0.005284,0.020597,0.003336,1.0,1.0
270952,0.5,0.000164,0.003411,0.145841,0.0,0.000280,0.321189,0.2500,3.0,0.000000,...,0.178161,0.035461,0.006282,0.003414,0.024191,0.019815,0.020597,0.004713,0.0,1.0
270953,0.5,0.000000,0.010914,0.291681,0.0,0.000000,-1.000000,0.0000,4.0,0.000000,...,0.011494,0.058859,0.011526,0.182743,0.040467,0.000661,0.112085,0.001517,1.0,1.0
270954,0.0,0.000000,0.004775,0.291681,0.0,0.000000,-1.000000,0.0000,9.0,0.000000,...,0.017241,0.056826,0.020489,0.000405,0.023915,0.003303,0.023433,0.003758,1.0,1.0

In [15]:
df_dropped_all.to_pickle("../../Base de datos/Processed/nn_challenge_test_clean.pkl")