In [12]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt
import seaborn as sns

In [82]:
df = pd.read_pickle('../../Base de datos/nocategorical.pkl')
df

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
0,0.554222,1.0,0.0,0.000000,0.398189,0.000000,0.190514,0.774141,0.004995,0.666667,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
1,0.521013,0.5,0.0,NaN,0.299222,0.000649,0.000000,0.827157,0.000668,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
2,0.545612,1.0,0.0,0.000102,0.248790,0.000000,0.571429,0.851531,0.000604,0.000000,...,0.206293,0.022686,0.000562,0.50000,0.116689,0.566809,0.020597,0.020891,1.0,1
3,0.593774,0.5,0.0,0.000000,0.412052,0.001299,0.087886,0.559571,0.002227,0.333333,...,0.026009,0.074658,0.003375,1.00000,0.025595,0.097360,0.020597,0.002580,0.0,1
4,0.278900,0.0,0.0,0.000000,0.160199,0.009740,0.134400,0.841197,0.000700,0.833333,...,0.049540,0.064444,0.003375,0.85715,0.032973,0.131737,0.020597,0.002613,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472417,0.423788,0.0,0.0,0.000000,0.485636,0.018182,0.285714,0.792730,0.004645,0.333333,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
472418,0.539659,0.5,0.0,0.000105,0.158255,0.005844,0.114286,0.517002,0.002545,0.500000,...,0.112360,0.020824,0.004499,0.85000,0.042598,0.189578,0.020597,0.003336,1.0,1
472419,0.435566,0.5,0.0,0.000164,0.423629,0.003247,0.142857,0.801128,0.000859,0.666667,...,0.064070,0.030698,0.016873,0.92645,0.031424,0.202529,0.020597,0.004713,0.0,1
472420,0.395057,0.5,0.0,0.000000,0.340654,0.010390,0.285714,0.731666,0.000700,0.000000,...,0.039394,0.112085,0.000562,0.50000,0.040467,0.101130,0.112085,0.001517,1.0,1
472421,0.340031,0.0,0.0,0.000000,0.383177,0.004545,0.285714,0.877686,0.001145,0.000000,...,0.045928,0.059760,0.002812,0.90000,0.030159,0.114229,0.023433,0.003758,1.0,1

In [87]:
# Contar la cantidad de cada valor único en la columna 'Target'
value_counts = df['target'].value_counts()

# Calcular la proporción entre los valores 0 y 1
proportion = value_counts[0] / value_counts[1]
proportion

0.16372710342992836

In [33]:
dfcopy = df.copy()

In [84]:
df_dropped_all = df.dropna()
df_dropped_all

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
3,0.593774,0.5,0.0,0.000000,0.412052,0.001299,0.087886,0.559571,0.002227,0.333333,...,0.026009,0.074658,0.003375,1.00000,0.025595,0.097360,0.020597,0.002580,0.0,1
6,0.455957,1.0,0.0,0.000018,0.272786,0.014286,0.571429,0.796988,0.001050,0.500000,...,0.176415,0.238134,0.005062,0.80770,0.043148,0.229013,0.199603,0.004473,0.0,1
7,0.675143,1.0,0.0,0.000259,0.331525,0.040909,0.571429,0.880024,0.000923,0.750000,...,0.211176,0.106760,0.001125,0.75000,0.122571,0.217953,0.106760,0.005346,0.0,1
10,0.420651,0.5,0.0,0.000120,0.658876,0.005844,0.263771,0.703912,0.001273,0.333333,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,1
11,0.517382,0.5,0.0,0.000164,0.234664,0.017532,0.571429,0.817447,0.000032,1.000000,...,0.203932,0.020992,0.000562,0.50000,0.100911,0.265197,0.020597,0.005515,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467454,0.602052,0.5,0.0,0.000000,0.308753,0.070779,0.285714,0.859670,0.000859,0.500000,...,0.085892,0.022177,0.002812,0.75000,0.050887,0.237017,0.020597,0.006062,0.0,1
467457,0.488040,1.0,0.0,0.000163,0.387654,0.000000,0.163314,0.853657,0.000064,1.000000,...,0.135308,0.069309,0.001687,0.60000,0.074664,0.351867,0.069309,0.006433,0.0,1
467459,0.443471,0.5,0.0,0.000125,0.436325,0.000000,0.380914,0.451087,0.001273,0.333333,...,0.113105,0.116021,0.014623,0.90325,0.033008,0.240204,0.045383,0.004853,0.0,1
467461,0.560547,0.5,0.0,0.000078,0.252033,0.035714,0.000000,0.704945,0.002195,0.666667,...,0.199900,0.119463,0.001125,0.66665,0.092646,0.226892,0.020597,0.006386,0.0,1
467467,0.728317,0.5,0.0,0.000000,0.265570,0.010390,0.489829,0.817631,0.001845,0.666667,...,0.047132,0.022517,0.002250,0.63635,0.036783,0.165484,0.020597,0.002218,0.0,1

In [88]:
# Contar la cantidad de cada valor único en la columna 'Target'
value_counts = df_dropped_all['target'].value_counts()

# Calcular la proporción entre los valores 0 y 1
proportion = value_counts[0] / value_counts[1]
proportion

0.16056078751540553

## Quitamos valores NaN

In [41]:
dfcopy.isna().sum()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472417,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
472418,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
472419,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
472420,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
472421,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [46]:
# Encontrar nombres de columnas con NaN
nan_columns_list = [col for col in df.columns if df[col].isna().any()]

# Mostrar la lista de columnas
print(nan_columns_list)

['feature_2', 'feature_3', 'feature_4', 'feature_6', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_15', 'feature_16', 'feature_19', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_88', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'feature_100', 'feature_101', 'feature_102', 'feature_103', 'feature_104', 'feature_105', 'feature_106', 'feature_107', 'feature_108', 'feature_109', 'feature_110', 'feature_111', 'feature_112', 'feature_113', 'feature_116', 'feature_120', 'feature_121', 'feature_122', 'feature_123', 'feature_124', 'feature_125', 'feature_126', 'feature_128', 'feature_129', 'feature_130', 'feature_131', 'feature_132', 'feature_133', 'feature_134', 'feature_135', 'feature_137', 'feature_140', 'feature_145', 'feature_146', 'feature_149', 'feature_150', 'feature_151', 'feature_152', 'feature_153', 'feature_154', 'feature_155', 'feature_156', 'feature_157', 'feature_160', 'feature_161', 'feature_165', 'feature_166', 'feature_167', 'feature_168', 'feature_169', 'feature_170', 'feature_171', 'feature_172', 'feature_173', 'feature_174', 'feature_175', 'feature_176', 'feature_177', 'feature_178', 'feature_179', 'feature_180', 'feature_181', 'feature_182', 'feature_183', 'feature_184', 'feature_185', 'feature_186', 'feature_187', 'feature_188', 'feature_190', 'feature_191', 'feature_192', 'feature_193', 'feature_196', 'feature_197', 'feature_198', 'feature_199', 'feature_200', 'feature_201', 'feature_202', 'feature_203', 'feature_204', 'feature_205', 'feature_206', 'feature_207', 'feature_208', 'feature_209', 'feature_210', 'feature_211', 'feature_212', 'feature_213', 'feature_214', 'feature_215', 'feature_216', 'feature_217', 'feature_218']

In [70]:
# Contar el número de NaN en cada columna
nan_count = df.isnull().sum()

# Filtrar columnas donde el número de NaN es mayor que 10
columns_with_more_than_10_nans = nan_count[nan_count > 40000]

len(columns_with_more_than_10_nans)

1

In [71]:
# Ordenar las columnas por la cantidad de valores NaN
sorted_columns_by_nan_count = nan_count.sort_values(ascending=False)

sorted_columns_by_nan_count

feature_15     117925
feature_182     39001
feature_172     38995
feature_170     38955
feature_177     38883
                ...
feature_119         0
feature_118         0
feature_117         0
feature_115         0
target              0
Length: 219, dtype: int64

In [72]:
# Eliminar filas donde la columna 'A' tiene valores NaN
df_dropped = df.dropna(subset=['feature_182'])

In [77]:
# Encontrar nombres de columnas con NaN
nan_columns_list = [col for col in df_dropped.columns if df_dropped[col].isna().any()]

# Mostrar la lista de columnas
print(len(nan_columns_list))

169

In [81]:
df_dropped

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
0,0.554222,1.0,0.0,0.000000,0.398189,0.000000,0.190514,0.774141,0.004995,0.666667,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
2,0.545612,1.0,0.0,0.000102,0.248790,0.000000,0.571429,0.851531,0.000604,0.000000,...,0.206293,0.022686,0.000562,0.50000,0.116689,0.566809,0.020597,0.020891,1.0,1
3,0.593774,0.5,0.0,0.000000,0.412052,0.001299,0.087886,0.559571,0.002227,0.333333,...,0.026009,0.074658,0.003375,1.00000,0.025595,0.097360,0.020597,0.002580,0.0,1
4,0.278900,0.0,0.0,0.000000,0.160199,0.009740,0.134400,0.841197,0.000700,0.833333,...,0.049540,0.064444,0.003375,0.85715,0.032973,0.131737,0.020597,0.002613,1.0,1
5,0.364791,0.5,0.0,0.000000,0.318264,0.001948,0.415543,0.605981,0.000827,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472417,0.423788,0.0,0.0,0.000000,0.485636,0.018182,0.285714,0.792730,0.004645,0.333333,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
472418,0.539659,0.5,0.0,0.000105,0.158255,0.005844,0.114286,0.517002,0.002545,0.500000,...,0.112360,0.020824,0.004499,0.85000,0.042598,0.189578,0.020597,0.003336,1.0,1
472419,0.435566,0.5,0.0,0.000164,0.423629,0.003247,0.142857,0.801128,0.000859,0.666667,...,0.064070,0.030698,0.016873,0.92645,0.031424,0.202529,0.020597,0.004713,0.0,1
472420,0.395057,0.5,0.0,0.000000,0.340654,0.010390,0.285714,0.731666,0.000700,0.000000,...,0.039394,0.112085,0.000562,0.50000,0.040467,0.101130,0.112085,0.001517,1.0,1
472421,0.340031,0.0,0.0,0.000000,0.383177,0.004545,0.285714,0.877686,0.001145,0.000000,...,0.045928,0.059760,0.002812,0.90000,0.030159,0.114229,0.023433,0.003758,1.0,1

In [80]:
# Contar el número de NaN en cada columna
nan_count = df_dropped.isnull().sum()

# Filtrar columnas donde el número de NaN es mayor que 10
columns_with_more_than_10_nans = nan_count[nan_count > 30000]

len(columns_with_more_than_10_nans)

1

In [ ]:
# Ordenar las columnas por la cantidad de valores NaN
sorted_columns_by_nan_count = nan_count.sort_values(ascending=False)

sorted_columns_by_nan_count

In [34]:
correlation_matrix = dfcopy.corr().abs()

In [35]:
upper_triangle = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))

In [36]:
to_drop = [column for column in upper_triangle.columns if any(upper_triangle[column] > 0.9)]

In [37]:
df_dropped = dfcopy.drop(dfcopy[to_drop], axis=1)

In [38]:
df_dropped

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_210,feature_211,feature_212,feature_213,feature_214,feature_215,feature_216,feature_217,feature_218,target
0,0.554222,1.0,0.0,0.000000,0.398189,0.000000,0.190514,0.774141,0.004995,0.666667,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
1,0.521013,0.5,0.0,NaN,0.299222,0.000649,0.000000,0.827157,0.000668,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
2,0.545612,1.0,0.0,0.000102,0.248790,0.000000,0.571429,0.851531,0.000604,0.000000,...,0.206293,0.022686,0.000562,0.50000,0.116689,0.566809,0.020597,0.020891,1.0,1
3,0.593774,0.5,0.0,0.000000,0.412052,0.001299,0.087886,0.559571,0.002227,0.333333,...,0.026009,0.074658,0.003375,1.00000,0.025595,0.097360,0.020597,0.002580,0.0,1
4,0.278900,0.0,0.0,0.000000,0.160199,0.009740,0.134400,0.841197,0.000700,0.833333,...,0.049540,0.064444,0.003375,0.85715,0.032973,0.131737,0.020597,0.002613,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472417,0.423788,0.0,0.0,0.000000,0.485636,0.018182,0.285714,0.792730,0.004645,0.333333,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.0,1
472418,0.539659,0.5,0.0,0.000105,0.158255,0.005844,0.114286,0.517002,0.002545,0.500000,...,0.112360,0.020824,0.004499,0.85000,0.042598,0.189578,0.020597,0.003336,1.0,1
472419,0.435566,0.5,0.0,0.000164,0.423629,0.003247,0.142857,0.801128,0.000859,0.666667,...,0.064070,0.030698,0.016873,0.92645,0.031424,0.202529,0.020597,0.004713,0.0,1
472420,0.395057,0.5,0.0,0.000000,0.340654,0.010390,0.285714,0.731666,0.000700,0.000000,...,0.039394,0.112085,0.000562,0.50000,0.040467,0.101130,0.112085,0.001517,1.0,1
472421,0.340031,0.0,0.0,0.000000,0.383177,0.004545,0.285714,0.877686,0.001145,0.000000,...,0.045928,0.059760,0.002812,0.90000,0.030159,0.114229,0.023433,0.003758,1.0,1